In [ ]:
import numpy as np

# Indexing and slicing

arr = np.array([10, 20, 30, 40, 50])

print(arr[0])
print(arr[-1])
print(arr[1:4])


10
50
[20 30 40]


In [3]:
# 2D 
arr = np.array([[1,2,3],[4,5,6]])

print(arr[0, 1])   # row 0, column 1

print(arr)


2
[[1 2 3]
 [4 5 6]]


In [4]:
arr = np.array([1, 2, 3, 4])
print(arr ** 2)


[ 1  4  9 16]


In [ ]:
# Even or odd

arr = np.array([1, 2, 3, 4, 5, 6])
print(arr[arr % 2 == 0])


[2 4 6]
